#!/bin/bash

function check_okay {
   if [ $? -ne 0 ]; then
      echo
      echo "FAILED"
      echo
      exit 1
   fi
}


[[ -r lib ]] && rm -rf lib

[[ -r include ]] && rm -rf include

cd src;

cd ce; ./clean; check_okay;

cd ../core_collapse; ./clean; check_okay;
