#!/bin/bash

function check_okay {
   if [ $? -ne 0 ]; then
      echo
      echo "FAILED"
      echo
      exit 1
   fi
}


if [ ! -r lib ]; then
   mkdir lib
fi

if [ ! -r include ]; then
   mkdir include
fi
check_okay;

cd src;
cd ce; ./clean; check_okay;
./mk; check_okay;
./export;

cd ../core_collapse; ./clean; check_okay;
./mk; check_okay;
./export;
