#!/bin/bash


# always remove restart file to start a fresh simulation
rm -f .restart

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

if [[ -e bin2dc0.exe ]]; then

	./binary.exe

else

   if [ "$#" -eq 0 ]; then
      ./binary
   elif [ "$#" -eq 1 ]; then
      export MESA_TEMP_CACHES_DIR=$PWD/.mesa_temp_cache/$1
      ./binary $1
      rm -rf $MESA_TEMP_CACHES_DIR
   else
      printf "\nERROR: more arguments than needed were given \n\n"
      exit 1
   fi

fi

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

exit 0
